apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  labels:
    app: user-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
        - name: user-api
          image: alyanovao/user-api:1.0.3-snapshot
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: user-api-configmap
                  key: java-opts
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: datasource-url
                  name: user-api-configmap
            - name: SPRING_DATASOURCE_HIKARI_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: secret-db
            - name: SPRING_DATASOURCE_HIKARI_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: secret-db