apiVersion: v1
kind: Service
metadata:
  name: delivery
  labels:
    app: order-microservice-app
spec:
  type: ClusterIP
  selector:
    service: delivery
  ports:
    - port: 8802
      name: web
      protocol: TCP
      targetPort: 8802