apiVersion: v1
kind: Service
metadata:
  name: notification
  labels:
    app: order-microservice-app
spec:
  type: ClusterIP
  selector:
    service: notification
  ports:
    - port: 8803
      name: web
      protocol: TCP
      targetPort: 8803