apiVersion: v1
kind: Service
metadata:
  name: store
  labels:
    app: order-microservice-app
spec:
  type: ClusterIP
  selector:
    service: store
  ports:
    - port: 8801
      name: web
      protocol: TCP
      targetPort: 8801