apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "user-api.fullname" . }}-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "user-api.fullname" . }}-service
                port:
                  number: {{ .Values.service.targetPort }}
          - path: {{ .Values.ingress.actuatorPath }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "user-api.fullname" . }}-service
                port:
                  number: {{ .Values.service.targetPort }}