apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret-db
  labels:
    {{- include "user-api.labels" . | nindent 4}}
type: Opaque
data:
  username: {{ .Values.secretDatabase.username }}
  password: {{ .Values.secretDatabase.password }}