apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-api.fullname" . }}-service
  labels:
  {{- include "user-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{ include "user-api.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      name: metrics
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}