version: "3.9"
services:
  postgres:
    image: postgres:13.3
    container_name: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - network
  user-api:
    image: alyanovao/user-api:1.0.1
    container_name: user-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_HIKARI_USERNAME: postgres
      SPRING_DATASOURCE_HIKARI_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - network
networks:
  network: