apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: customservice
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /otusapp/alyanov/(.+)
            pathType: ImplementationSpecific
            backend:
              service:
                name: customservice
                port:
                  number: 8001
          - path: /(.+)
            pathType: ImplementationSpecific
            backend:
              service:
                name: customservice
                port:
                  number: 8001
