version: '3'
services:
  customService:
    image: alyanovao/customservice:1.0.0
    container_name: "customService"
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - JAVA_OPTS=-Xms128m-Xmx128m
    networks:
      - network
networks:
  network: