apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
  labels:
    app: order-microservice-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-microservice-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: order-microservice-app
    spec:
      containers:
        - name: orderservice
          image: alyanovao/orderservice:1.0.1
          ports:
            - containerPort: 8008
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: order-microservice-app-configmap
                  key: java-opts
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: datasource-url
                  name: order-microservice-app-configmap
            - name: SPRING_DATASOURCE_HIKARI_USERNAME
              valueFrom:
                secretKeyRef:
                  key: order-username
                  name: secret-db
            - name: SPRING_DATASOURCE_HIKARI_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: order-password
                  name: secret-db
            - name: EXTERNAL_BILLING_HOST
              value: billing.default.svc.cluster.local
            - name: EXTERNAL_NOTIFICATION_HOST
              value: notification.default.svc.cluster.local