apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-api-monitor
  labels:
    app.kubernetes.io/name: user-api
    
spec:
  endpoints:
    - port: metrics
      scrapeTimeout: 5s
      path: /actuator/prometheus     
      honorLabels: true
      scheme: http
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/instance: user-api
      app.kubernetes.io/name: user-api