# Default values for user-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

secretDatabase:
  username: "postgres"
  password: "postgres"

userApiConfig:
  javaOpts: "-Xms128m-Xmx128m"
  url: "jdbc:postgresql://postgres-db-postgresql.postgres.svc.cluster.local:5432/postgres"

deployment:
  replicaCount: 1
  strategy: Recreate
  repository: "alyanovao/user-api"
  version: "1.0.0"
  port: 8080

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080


ingress:
  host: arch.homework
  path: "/user"
  pathType: "Prefix"

migration:
  restartPolicy: Never
  containerName: create-table
  host: "postgres-db-postgresql.postgres.svc.cluster.local"
  image: docker.io/bitnami/postgresql:14.4.0-debian-11-r13
  backOffLimit: 0